"""
PDF export service.

Generates branded KRONOS CORE PDFs using reportlab.
All functions accept a plain dict and return raw PDF bytes.
No network calls, no secrets, no side effects.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

import structlog

log = structlog.get_logger()

# ── Colours (hex strings) ─────────────────────────────────────────────────────
_GREEN  = "#00cc55"   # slightly dimmed brand green — readable on white
_DARK   = "#0d1117"
_GRAY   = "#444444"
_LGRAY  = "#888888"
_WHITE  = "#ffffff"


def _rl():
    """Lazy import of reportlab — raises ImportError with clear message if missing."""
    try:
        import reportlab  # noqa: F401
        return True
    except ImportError as exc:
        raise ImportError(
            "reportlab is not installed. Run: pip install reportlab"
        ) from exc


def _make_doc(buf: io.BytesIO):
    from reportlab.lib.pagesizes import A4
    from reportlab.platypus import SimpleDocTemplate
    from reportlab.lib.units import mm

    return SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=22 * mm,
        leftMargin=22 * mm,
        topMargin=22 * mm,
        bottomMargin=22 * mm,
    )


def _styles():
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.lib.enums import TA_CENTER

    base = getSampleStyleSheet()
    GREEN = HexColor(_GREEN)
    DARK  = HexColor(_DARK)
    GRAY  = HexColor(_GRAY)
    LGRAY = HexColor(_LGRAY)

    return {
        "title": ParagraphStyle(
            "KTitle", parent=base["Normal"],
            textColor=DARK, fontSize=22, leading=28,
            fontName="Helvetica-Bold", spaceAfter=2,
        ),
        "subtitle": ParagraphStyle(
            "KSubtitle", parent=base["Normal"],
            textColor=GREEN, fontSize=13, leading=16,
            fontName="Helvetica-Bold", spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            "KH2", parent=base["Normal"],
            textColor=GREEN, fontSize=10, leading=14,
            fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "KBody", parent=base["Normal"],
            textColor=GRAY, fontSize=9, leading=14, spaceAfter=2,
        ),
        "bullet": ParagraphStyle(
            "KBullet", parent=base["Normal"],
            textColor=GRAY, fontSize=9, leading=13,
            leftIndent=12, spaceAfter=2,
        ),
        "small": ParagraphStyle(
            "KSmall", parent=base["Normal"],
            textColor=LGRAY, fontSize=7.5, leading=11,
        ),
        "footer": ParagraphStyle(
            "KFooter", parent=base["Normal"],
            textColor=LGRAY, fontSize=7.5, leading=10,
            alignment=TA_CENTER,
        ),
        "meta": ParagraphStyle(
            "KMeta", parent=base["Normal"],
            textColor=LGRAY, fontSize=8, leading=12, spaceAfter=2,
        ),
        "badge": ParagraphStyle(
            "KBadge", parent=base["Normal"],
            textColor=HexColor(_GREEN), fontSize=8,
            fontName="Helvetica-Bold", leading=12, spaceAfter=4,
        ),
    }


def _hr(color=_GREEN, thickness=1.5):
    from reportlab.platypus import HRFlowable
    from reportlab.lib.colors import HexColor
    return HRFlowable(width="100%", thickness=thickness, color=HexColor(color), spaceAfter=4)


def _sp(mm_val=4):
    from reportlab.platypus import Spacer
    from reportlab.lib.units import mm
    return Spacer(1, mm_val * mm)


def _bullets(items: list, style, prefix="•") -> list:
    from reportlab.platypus import Paragraph
    return [Paragraph(f"{prefix}  {item}", style) for item in items if item]


def _section(title: str, story: list, styles: dict):
    from reportlab.platypus import Paragraph
    story.append(Paragraph(title, styles["h2"]))
    story.append(_hr(color=_GREEN, thickness=0.5))


def _footer_text() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"Generated by KRONOS CORE — Autonomous Security & Prompt Architecture Gateway · {ts} · CONFIDENTIAL"


# ── Enterprise Report PDF ─────────────────────────────────────────────────────

def build_enterprise_report_pdf(report_data: dict) -> bytes:
    _rl()
    from reportlab.platypus import Paragraph

    buf = io.BytesIO()
    doc = _make_doc(buf)
    s   = _styles()

    story: list[Any] = []

    # Header block
    story.append(Paragraph("KRONOS CORE", s["title"]))
    story.append(Paragraph("Enterprise Security Report", s["subtitle"]))
    story.append(_hr())
    story.append(_sp(4))

    # Metadata
    story.append(Paragraph(f"Product: {report_data.get('product', 'KRONOS CORE')}", s["meta"]))
    story.append(Paragraph(f"Report ID: {report_data.get('report_id', 'N/A')}", s["meta"]))
    story.append(Paragraph(f"Generated: {report_data.get('generated_at', 'N/A')}", s["meta"]))
    story.append(Paragraph("★  ENTERPRISE READY", s["badge"]))
    story.append(_sp(3))

    # Executive Summary
    _section("Executive Summary", story, s)
    story.append(Paragraph(report_data.get("executive_summary", ""), s["body"]))
    story.append(_sp(3))

    # Capabilities
    _section("Capabilities", story, s)
    story.extend(_bullets(report_data.get("capabilities", []), s["bullet"]))
    story.append(_sp(3))

    # Compliance
    _section("Compliance Alignment", story, s)
    story.extend(_bullets(report_data.get("compliance_alignment", []), s["bullet"]))
    story.append(_sp(3))

    # Integration + Deployment
    _section("Integration Options", story, s)
    story.extend(_bullets(report_data.get("integration_options", []), s["bullet"]))
    story.append(_sp(3))

    _section("Deployment Models", story, s)
    story.extend(_bullets(report_data.get("deployment_models", []), s["bullet"]))
    story.append(_sp(3))

    # Pricing
    _section("Pricing Model", story, s)
    story.append(Paragraph(report_data.get("pricing_model", ""), s["body"]))
    story.append(_sp(3))

    # Support
    _section("Support Model", story, s)
    story.append(Paragraph(report_data.get("support_model", ""), s["body"]))
    story.append(_sp(3))

    # References
    _section("References & Standards", story, s)
    story.extend(_bullets(report_data.get("references", []), s["small"]))
    story.append(_sp(8))

    # Footer
    story.append(_hr(color=_LGRAY, thickness=0.5))
    story.append(Paragraph(_footer_text(), s["footer"]))

    doc.build(story)
    log.info("pdf_built", report_type="enterprise", size_bytes=buf.tell())
    return buf.getvalue()


# ── Blueprint Report PDF ──────────────────────────────────────────────────────

def build_blueprint_report_pdf(report_data: dict) -> bytes:
    _rl()
    from reportlab.platypus import Paragraph

    buf = io.BytesIO()
    doc = _make_doc(buf)
    s   = _styles()

    story: list[Any] = []

    story.append(Paragraph("KRONOS CORE", s["title"]))
    story.append(Paragraph("Secure Execution Blueprint", s["subtitle"]))
    story.append(_hr())
    story.append(_sp(4))

    story.append(Paragraph(f"Blueprint ID: {report_data.get('blueprint_id', 'N/A')}", s["meta"]))
    story.append(Paragraph(f"Generated: {report_data.get('generated_at', 'N/A')}", s["meta"]))

    risk = report_data.get("risk_score", {})
    if risk:
        story.append(Paragraph(
            f"Risk Score: {risk.get('overall', 'N/A')} / 100  —  Level: {risk.get('level', 'N/A')}",
            s["badge"],
        ))
    story.append(_sp(3))

    _section("Objective Summary", story, s)
    story.append(Paragraph(report_data.get("objective_summary", ""), s["body"]))
    story.append(_sp(3))

    _section("Secure Coding Standards", story, s)
    story.extend(_bullets(report_data.get("secure_coding_standards", []), s["bullet"]))
    story.append(_sp(3))

    pkg = report_data.get("package_policy", {})
    if pkg:
        _section("Package Policy — Allowed", story, s)
        story.extend(_bullets(pkg.get("allowed", []), s["bullet"], prefix="✓"))
        story.append(_sp(2))
        _section("Package Policy — Forbidden", story, s)
        story.extend(_bullets(pkg.get("forbidden", []), s["bullet"], prefix="✗"))
        story.append(_sp(3))

    _section("Deployment Checklist", story, s)
    story.extend(_bullets(report_data.get("deployment_checklist", []), s["bullet"]))
    story.append(_sp(3))

    _section("Production Readiness Checklist", story, s)
    story.extend(_bullets(report_data.get("production_readiness_checklist", []), s["bullet"]))
    story.append(_sp(8))

    story.append(_hr(color=_LGRAY, thickness=0.5))
    story.append(Paragraph(_footer_text(), s["footer"]))

    doc.build(story)
    log.info("pdf_built", report_type="blueprint", size_bytes=buf.tell())
    return buf.getvalue()


# ── Audit Report PDF ──────────────────────────────────────────────────────────

def build_audit_report_pdf(report_data: dict) -> bytes:
    _rl()
    from reportlab.platypus import Paragraph, Table, TableStyle
    from reportlab.lib.colors import HexColor, white

    buf = io.BytesIO()
    doc = _make_doc(buf)
    s   = _styles()

    story: list[Any] = []

    story.append(Paragraph("KRONOS CORE", s["title"]))
    story.append(Paragraph("NPM Package Security Audit", s["subtitle"]))
    story.append(_hr())
    story.append(_sp(4))

    story.append(Paragraph(f"Audit ID: {report_data.get('audit_id', 'N/A')}", s["meta"]))
    story.append(Paragraph(f"Audited: {report_data.get('audited_at', 'N/A')}", s["meta"]))

    summary = report_data.get("summary", {})
    if summary:
        verdict = summary.get("overall_verdict", "N/A")
        story.append(Paragraph(
            f"Verdict: {verdict}  —  Total: {summary.get('total', 0)}  "
            f"Safe: {summary.get('safe', 0)}  "
            f"Flagged: {summary.get('flagged', 0)}  "
            f"Dangerous: {summary.get('dangerous', 0)}",
            s["badge"],
        ))
    story.append(_sp(3))

    results = report_data.get("results", [])
    if results:
        _section("Package Results", story, s)
        table_data = [["Package", "Risk", "Reason"]]
        for r in results:
            table_data.append([
                str(r.get("name", "")),
                str(r.get("risk", "")),
                str(r.get("reason", ""))[:80],
            ])
        tbl = Table(table_data, colWidths=["25%", "15%", "60%"])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor(_DARK)),
            ("TEXTCOLOR",  (0, 0), (-1, 0), white),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 7.5),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#f9f9f9"), HexColor(_WHITE)]),
            ("GRID",       (0, 0), (-1, -1), 0.25, HexColor("#cccccc")),
            ("LEFTPADDING",  (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING",   (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 3),
        ]))
        story.append(tbl)
        story.append(_sp(4))

    _section("Recommendations", story, s)
    story.extend(_bullets(report_data.get("recommendations", []), s["bullet"]))
    story.append(_sp(8))

    story.append(_hr(color=_LGRAY, thickness=0.5))
    story.append(Paragraph(_footer_text(), s["footer"]))

    doc.build(story)
    log.info("pdf_built", report_type="audit", size_bytes=buf.tell())
    return buf.getvalue()
